# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/logging.h \
    ./src/tabcontrollers/DeviceManipulationTabController.h \
    ./src/overlaycontroller.h \
    C:\Users\bonsi\Downloads\OpenVR-MC\openvr\headers\openvr.h
SOURCES += ./Debug/moc_DeviceManipulationTabController.cpp \
    ./Debug/moc_overlaycontroller.cpp \
    ./src/tabcontrollers/DeviceManipulationTabController.cpp \
    ./src/main.cpp \
    ./src/overlaycontroller.cpp
