# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./src/logging.h \
    ./src/overlaycontroller.h \
    ./src/tabcontrollers/DeviceManipulationTabController.h \
    ./src/QGlobalShortcut/qglobalshortcut.h
SOURCES += ./src/main.cpp \
    ./src/overlaycontroller.cpp \
    ./src/tabcontrollers/DeviceManipulationTabController.cpp \
    ./src/QGlobalShortcut/qglobalshortcut.cpp
